### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by cadeath** [cadeath/Dalton#11] opened 2016-04-27 06:59 UTC
UPDATE 12/22/16

1. Include Logs for user's who create another users and change/add privilege
2. Disable/Enable users
3. User Log - Login/Logout

----------------------------------------------------------------------------------------------
Access Rights/Privileges should be added in the SPECIAL RIGHTS
This is to eliminate any unnecessary privileges to be added

**Comment by marzxxx90** [comment] 2016-06-02 01:05
Added privilege check box in tbPrivilege special tab
Only have privilege can add privilege to user accounts

**Comment by marzxxx90** [comment] 2016-06-02 05:20
Added trap to txtuser.txt to avoid duplicate of username

**Comment by marzxxx90** [comment] 2016-06-06 03:46
For Checking

**Comment by cadeath** [comment] 2016-06-07 09:02
What Branch?

**Comment by Arskie** [comment] 2016-06-08 02:22
"User management" dapad di maka add og user pag wala naka butang og username og fullname.

**Comment by Arskie** [comment] 2016-06-08 02:33
"User management suggestion" dapat maka delete og user pag daghan na ka a u ang naka registered na user.

**Comment by cadeath** [comment] 2016-06-08 02:53
remove
CheckUsername on Ln 229 - 243

**Comment by cadeath** [comment] 2016-06-08 03:12
Check User was revised and included to ComputerUser Class before saving

**Comment by cadeath** [comment] 2016-06-08 03:13
Cannot ADD USER

**Comment by cadeath** [comment] 2016-06-08 03:13
Please ENUMERATE all the changes on this BRANCH

**Comment by marzxxx90** [comment] 2016-06-08 06:20
Added Reset Password and Privilege checkbox
only user can add privilege to other user if their user privilege check and 
only user can change password to other user if their user reset password check

**Comment by cadeath** [comment] 2016-06-08 08:25
**Please follow these revisions**

1. Adding User won't ask AUTHORIZATION
2. Check user before adding to verify duplication
3. Changing password is allowable to all users, just add CHANGE PASSWORD in the FILE MENU
4. Reset Password is base on PRIVILEGE

**Comment by marzxxx90** [comment] 2016-06-09 06:36
default na ang appraiser sa encoder sir? or sa tanan user?

**Comment by cadeath** [comment] 2016-06-10 02:12
uu default sa tanang EXISTING users.
pero pagmagHimo kag new Dili xa Default.

**Comment by cadeath** [comment] 2016-06-21 02:12
any update?

**Comment by marzxxx90** [comment] 2016-07-09 04:03
nag add ko ug patch para ma defualt appraiser ang tanan existing user
updated na pud ni sa 122
branch user management

**Comment by cadeath** [comment] 2016-07-25 03:27
Please verify if included in 1.2.2.8

**Comment by marzxxx90** [comment] 2016-07-27 03:32
wla ni na sabay sa 1228 sir..pero updated ni sa 1229

**Comment by cadeath** [comment] 2016-07-29 01:18
checking...

**Comment by cadeath** [comment] 2016-07-29 01:24
Please fix

**Comment by marzxxx90** [comment] 2016-07-29 02:02
fix na sir..gi change pa pud nko ang iyang patch

**Comment by cadeath** [comment] 2016-08-03 03:25
**Please follow these revisions**

1. Adding User won't ask AUTHORIZATION
2. Check user before adding to verify duplication
3. Changing password is allowable to all users, just add CHANGE PASSWORD in the FILE MENU
4. Reset Password is base on PRIVILEGE
5. User has default privilege as Appraiser


@Arskie @cloudNine09 @marzxxx90 

please verify

**Comment by marzxxx90** [comment] 2016-08-03 03:46
OK na ni sir..fix na ni tanan

**Comment by marzxxx90** [comment] 2016-08-04 04:09
Added Delete button to delete user

**Comment by cadeath** [comment] 2016-08-08 02:31
Give me update base on #47

**Comment by cadeath** [comment] 2016-08-08 02:32
Please update in the MASTER, not branch 122

**Comment by marzxxx90** [comment] 2016-08-11 01:28
Added Delete Button To Delete User
Already Updated From Master
Branch: User Management

**Comment by cadeath** [comment] 2016-12-19 08:43
BUG

Please check
Clickable UPDATE button for users unable to use USER MANAGEMENT

@marzxxx90 @cloudNine09

**Comment by cadeath** [comment] 2016-12-19 08:55
@cloudNine09 
Please assist us in checking this Module
Don't hesitate in giving comments and suggestion about the module so that we can turn-over this properly to the Operation

**Comment by cadeath** [comment] 2016-12-22 02:45
OP updated

**Comment by cloudNine09** [comment] 2016-12-22 03:33
Should have Label Name for Retyping Password.
Clickable Enable/Disable User, upon viewing of Users privilege.

**Comment by marzxxx90** [comment] 2017-01-03 01:59
Added Log for User, to record every In/Out of user and creating/updating of user
branch: User Management
Updated from 1.4 POS

**Closed** 2017-03-23 03:44 UTC
Labels: bug, CRITICAL, FOR CHECKING, URGENT
